# 公共配置文件
# @author Xiaohang
server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri:  ${GATEWAY_INTERFACE_URL:https://interface-production-b00a.up.railway.app}

          predicates:
            - Path=/**
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
#        - id: add_request_header_route
#          uri: http://localhost:8123
#          predicates:
#            - Path=/api/**
#          filters:
#            - AddRequestHeader=xiaohang, swag
#            - AddRequestParameter=name, dog
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/fallback
#        - id: xiaohang-fallback
#          uri: https://xiaohang.icu
#          predicates:
#            - Path=/fallback
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: trace



#dubbo:
#  application:
#    qos-enable: true
#    metadata-type: local
#    qos-port: 33333
#    qos-accept-foreign-ip: false
#    name: xiaohangapi-consumer
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    id: nacos-registry
#    address: nacos://${NACOS_SERVER:nacos-server:8848}
#    parameters:
#      namespace: public
#      username: nacos
#      password: nacos
#    check: false          # ← 加这行，注册中心不可用时不报错
#  consumer:
#    check: false
#  config-center:
#    enabled: false   # ← 加这行，服务提供者不存在时不报错
#  qos:
#    port: 33333
dubbo:
  application:
    name: xiaohangapi-consumer
    metadata-type: local
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
    ext-protocol: tri
    preferred-protocol: tri
  registry:
    address: N/A
  consumer:
    check: false
  config-center:
    enabled: false
  metadata-report:
    enabled: false
  provider:
    url: ${GATEWAY_DUBBO_URL:https://interface-production-b00a.up.railway.app}
